### ISSUE TITLE
Is that possible to get customized colors in a map with cartogram, something like creating a choropleth map?

### ISSUE THREAD

**Issue by junwang4** [Flow-Based-Cartograms/go_cart#14]
Currently, it seems that all states have the same color. How should I customize colors for different states?

**Comment by mgastner** [comment]
In ps_figure.c, edit after line 49:

```
    if(region_na[i] == 0){
      if (i == 0) {
	fprintf(ps_file, "gsave\n1 0 0 SRGB f\ngrestore\n0 SGRY s\n");
      } else {
	fprintf(ps_file, "gsave\n0.96 0.92 0.70 SRGB f\ngrestore\n0 SGRY s\n");
      }
    }
```

See attached screenshot for the result of this edit applied to the following example.

```
cartogram -eg usa_contiguous_arcgis.json -a usa_contiguous_electors.csv
```

![Screenshot from 2019-10-10 11-02-44](https://user-images.githubusercontent.com/19757680/66535890-c44e8480-eb4d-11e9-9ba0-71fc9e1a230b.png)

Let me know whether this helps.

**Comment by junwang4** [comment]
It works. It would be more convenient if the color can be added to the csv file, say, the usa_contiguous_electors.csv

**Comment by mgastner** [comment]
I agree. Thank you for the suggestion.

**Comment by johnyrufus** [comment]
Hi, 
Thanks for letting us know where to change this in the code.
I have a solution for this, with r,g,b values included in the csv file, can I submit a PR ?

**Comment by mgastner** [comment]
OK, we can take a look at it.

**Comment by johnyrufus** [comment]
Thanks for your reply. Before I submit a PR, can you let me know a couple of clarifications.

1) The current modificiations I did, am assuming by default r,g,b values will be present in the csv. Should this be okay ? in which case we need to change the example json and documentation OR should I change my code to use r,g,b values if one is provided or simply use a default color (the current yellow one) if rgb is not present for that row.

2) I am not using csv parser as of yet, using a similar style of sscanf already in the current version to read the r,g,b values. Should I switch to using a csv parser instead ?

**Comment by mgastner** [comment]
It would be nicer if the code were to check whether there is a column "color" (alternatively called "colour") or three columns "red", "green" and "blue" (alternatively "r", "g" and "b"). Otherwise the image would have some default colour. How would we want to handle hex codes? Is red on a scale from 0 to 255 or 0 to 1?

A proper CSV parser would of course be great. It's been raised as issue #16, so far without progress.

**Comment by johnyrufus** [comment]
Thanks for your reply. I currently have red, green, blue all accepting values between 0 and 1. 
I can change this to be between 0 and 255 if needed and normalize inside the code.

For the csv parser, the link you have provided points to "https://github.com/rgamble/libcsv" which appears to be a good option. By using that, we would add the installation of libcsv for mac and libcsv3 for linux . I am using a mac, so i can test it out on mac, but I am not sure if I will be able to test it on Linux or Windows (I will try my best to get hold of ubuntu / windows machine, and test it out there as well). Is that okay ?

Also, I found that for later versions of gcc/xcode in mac (I tested the installation in 2 recent macbooks , just to make sure and both were failing), the current version of code we have doesnot compile/link. I did not face this issue in a previous version of mac that had previous versions of gcc/xcode installed. 
This is related to the llvm ld used by mac, either my old mac had gnu ld installed which gracefully handles duplicate symbols or the later version of llvm ld strictly forbids duplicate symbols.

The error I was getting had to do with duplicate symbols, and looks like the linker that mac uses(atleast the latest version of it) llvm ld does not handle duplicate symbol declarations anymore and I had to make a few minor changes to handle this. I will open up a separate issue (https://github.com/Flow-Based-Cartograms/go_cart/issues/19) and will submit this PR first, as this is essential for me to submit the other ones. Kindly take a look and advice.

Thanks.

**Comment by mgastner** [comment]
In my experience, rgb values between 0 and 255 are more common in most applications. Postscript's normalization from 0 to 1 is rather an exception.
Any help with the CSV parser would be appreciated.
Regarding the duplicate symbols, please see my response on issue #19.

**Comment by johnyrufus** [comment]
Thanks for your reply. I will change r,g,b to take the range 0 to 255 and normalize in the code.
Will start working on the csv parser also.

**Comment by johnyrufus** [comment]
Hi, I created a PR for enabling color as input. Kindly review. (I have not yet added a csv parser, will implement that as a separate issue. Thanks)

https://github.com/Flow-Based-Cartograms/go_cart/pull/22

**Comment by johnyrufus** [comment]
This is how the cartogram now looks with the color input. (I downloaded the color template from go-cart.io website and converted the color codes to r,g,b and included those color values as part of the example csv file as input in sample_data/usa_contiguous_electors.csv)

![cartogram](https://user-images.githubusercontent.com/4510962/89846928-6573e600-db37-11ea-9f51-e4dcc326742f.png)
