### ISSUE TITLE
Iterations dont converge when data is skewed

### ISSUE THREAD

**Issue by johnyrufus** [Flow-Based-Cartograms/go_cart#18]
I am trying to do something simple as having data for only one state as 1 and all the other states are 0. 
This leads to a large area error and there is no convergence.

Please advice. Thanks.

**Comment by mgastner** [comment]
I agree that the code should end more gracefully. Please note that the current version is approaching the end of its life cycle. In the next version, I will aim to make the code more aware of the geometry behind the problem. This strategy would hopefully fix problems similar to yours.

This said, the data that you are entering really isn't suitable for a cartogram. If almost all regions have a data value of zero, it would be better to show the data as a bar chart. If large chunks of the map must disappear, you must accept severe distortions on a contiguous cartogram. The result, even if it can be technically calculated, would hardly be useful.

**Comment by johnyrufus** [comment]
Thanks for your reply. The idea is to show a time lapse video and on day 1, data starts with everything as 0.
Are there any pointers I can use, to fix this to get it to working for data like these. 
Also, any workaround to show data like these in cartograms. (like adding a small value 0.0001 as baseline, but I tried this and it didnt solve the issue). Thanks again.

**Comment by mgastner** [comment]
You can try a noncontiguous cartogram or proportional-symbol map. If your discrete cases have specific locations, a dot-density map may also work. Data with lots of zeros or extremely heterogeneous distributions are not ideally suited for density-equalizing projections. Graticule lines must be extremely curved. I agree that it would be nice if we still could in principle compute the map projection. With different data structures, I hope to get yet more elastic projections in the next version. However, I doubt you would find the result easily interpretable.

**Comment by johnyrufus** [comment]
Thanks for your reply and assisting with this issue.
