### ISSUE TITLE
Help needed in creating in-between frames

### ISSUE THREAD

**Issue by johnyrufus** [Flow-Based-Cartograms/go_cart#21]
Hi Professor,

I have the following scenario. I have a cartogram_1.json generated for day1 and cartogram_2.json generated for day2.
To create a smooth animation, I need to generate the in-between frames. I am using a simple linear interpolation and I have written a small python script that produces cartogram_12.json, where the co-ordinates are linear interpolation of the original 2 files. 
I would like to generate the eps file using cartogram_12.json as input, can you advice me, where all I need to make the changes in the code to get this done ?
(should I apply fill_with_density and immediately proceed on to generating eps using ps_figure, skipping all the integrations ?)

**Comment by mgastner** [comment]
In main.c, insert this return statement after line 245:

```
  /* Terminate before cartogram calculation. Input shown in map.eps. */
  return 0;
```

The file you're looking for is map.eps.

**Comment by johnyrufus** [comment]
Thank you Professor.
