### ISSUE TITLE
 Error with polygons while writing GeoJSON file.

### ISSUE THREAD

**Issue by Udneowi** [Flow-Based-Cartograms/go_cart#26]
Hi!

I'm trying to make a cartogram on Denmark but receiving the following error:

cartogram -eg dnk_processedmap.json -a dnk_data.csv
328 polygon(s), 99 region(s)
Using a 512 x 512 lattice with bounding box
	(701003.614834 6966353.519481 1889339.200285 8154689.104932).

Note: Enlarging extremely small regions using scaled perimeter threshold. Areas for these regions will be scaled up. To disable this, please add the -n flag.

No regions below minimum threshold.

Starting integration 1
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.534794e-01, delta_t = 1.945307e-02
iter = 20, t = 3.427079e-01, delta_t = 2.128623e-02
iter = 30, t = 5.221624e-01, delta_t = 1.746911e-02
iter = 40, t = 6.968793e-01, delta_t = 1.433648e-02
iter = 50, t = 8.489313e-01, delta_t = 1.568748e-02
iter = 60, t = 9.679356e-01, delta_t = 9.655758e-03
max. abs. area error: 1.102689
Starting integration 2
iter = 0, t = 0.000000e+00, delta_t = 7.508469e-04
iter = 10, t = 1.196657e-02, delta_t = 1.947503e-03
iter = 20, t = 3.821763e-02, delta_t = 2.841369e-03
iter = 30, t = 5.349249e-02, delta_t = 1.311662e-03
iter = 40, t = 7.439701e-02, delta_t = 3.402114e-03
iter = 50, t = 1.266124e-01, delta_t = 6.618156e-03
iter = 60, t = 1.951733e-01, delta_t = 7.241819e-03
iter = 70, t = 2.765639e-01, delta_t = 1.056567e-02
iter = 80, t = 3.764302e-01, delta_t = 1.156133e-02
iter = 90, t = 4.923663e-01, delta_t = 1.265081e-02
iter = 100, t = 6.345558e-01, delta_t = 1.384296e-02
iter = 110, t = 7.905472e-01, delta_t = 1.514745e-02
iter = 120, t = 9.667731e-01, delta_t = 1.657487e-02
max. abs. area error: 0.901275
Starting integration 3
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 4.352060e-01, delta_t = 3.784219e-02
iter = 30, t = 7.184496e-01, delta_t = 3.105619e-02
iter = 40, t = 9.894718e-01, delta_t = 1.911531e-02
max. abs. area error: 0.211827
Starting integration 4
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 5.727500e-01, delta_t = 6.727500e-02
max. abs. area error: 0.009244
correction_factor = 1.037296
Error with polygons while writing GeoJSON file. n_polyinreg[0] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[1] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[2] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[3] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[4] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[5] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[6] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[7] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[8] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[9] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[10] = 5 while n_holes = 5
Error with polygons while writing GeoJSON file. n_polyinreg[11] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[12] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[13] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[14] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[15] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[16] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[17] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[18] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[19] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[20] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[21] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[23] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[25] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[26] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[27] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[28] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[29] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[30] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[31] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[32] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[33] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[34] = 6 while n_holes = 6
Error with polygons while writing GeoJSON file. n_polyinreg[35] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[36] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[37] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[38] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[39] = 5 while n_holes = 5
Error with polygons while writing GeoJSON file. n_polyinreg[40] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[41] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[42] = 14 while n_holes = 14
Error with polygons while writing GeoJSON file. n_polyinreg[43] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[44] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[45] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[46] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[47] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[48] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[49] = 7 while n_holes = 7
Error with polygons while writing GeoJSON file. n_polyinreg[50] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[51] = 5 while n_holes = 5
Error with polygons while writing GeoJSON file. n_polyinreg[52] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[53] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[54] = 8 while n_holes = 8
Error with polygons while writing GeoJSON file. n_polyinreg[55] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[56] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[57] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[58] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[59] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[60] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[61] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[62] = 14 while n_holes = 14
Error with polygons while writing GeoJSON file. n_polyinreg[63] = 7 while n_holes = 7
Error with polygons while writing GeoJSON file. n_polyinreg[64] = 5 while n_holes = 5
Error with polygons while writing GeoJSON file. n_polyinreg[65] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[66] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[68] = 6 while n_holes = 6
Error with polygons while writing GeoJSON file. n_polyinreg[69] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[70] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[71] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[72] = 8 while n_holes = 8
Error with polygons while writing GeoJSON file. n_polyinreg[73] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[74] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[75] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[76] = 14 while n_holes = 14
Error with polygons while writing GeoJSON file. n_polyinreg[77] = 6 while n_holes = 6
Error with polygons while writing GeoJSON file. n_polyinreg[78] = 10 while n_holes = 10
Error with polygons while writing GeoJSON file. n_polyinreg[79] = 5 while n_holes = 5
Error with polygons while writing GeoJSON file. n_polyinreg[80] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[81] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[82] = 9 while n_holes = 9
Error with polygons while writing GeoJSON file. n_polyinreg[83] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[84] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[85] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[86] = 7 while n_holes = 7
Error with polygons while writing GeoJSON file. n_polyinreg[87] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[88] = 10 while n_holes = 10
Error with polygons while writing GeoJSON file. n_polyinreg[89] = 3 while n_holes = 3
Error with polygons while writing GeoJSON file. n_polyinreg[90] = 8 while n_holes = 8
Error with polygons while writing GeoJSON file. n_polyinreg[91] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[92] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[93] = 4 while n_holes = 4
Error with polygons while writing GeoJSON file. n_polyinreg[94] = 12 while n_holes = 12
Error with polygons while writing GeoJSON file. n_polyinreg[95] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[96] = 2 while n_holes = 2
Error with polygons while writing GeoJSON file. n_polyinreg[97] = 1 while n_holes = 1
Error with polygons while writing GeoJSON file. n_polyinreg[98] = 2 while n_holes = 2

Can you help me understanding what is wrong? It generates the image but I'm mostly interested in the GeoJson file.

**Comment by mgastner** [comment]
What geometry types are in dnk_processedmap.json? Only polygons and multipolygons are supported.

**Comment by Udneowi** [comment]
Thanks for the feedback!

It consists of polygons and multi polygons. I pretty much just followed the recommendations of getting the shape file from GADM and then through map shaper. I already had a file but just to replicate what was already recommended. It should be in geojson format from there. 

As said it does run. It just can't seem to create the GeoJSON file.

<img width="951" alt="Screenshot 2021-01-28 at 16 39 31" src="https://user-images.githubusercontent.com/25606256/106161565-7537c300-6187-11eb-98f3-cd7d886503ae.png">

**Comment by Udneowi** [comment]
@mgastner I have also tried to run the sample data which works fine without any error. However doing it all from the start does not work out for me. 

For some reproducibility one can do the following:

1. Download: https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_DNK_shp.zip
2. Put into map shaper and simplify with 25% on adm level 1 (only 5 polygons for quick computing)
         -proj +init=EPSG:3395
         simplify 25%
         -o format=geojson denmark.json
3. Run the preprocessing: cartogram -p denmark.json
4. Open the dnk_data.csv file and put in 1 in all the data points.
5. Run the algorithm which gives the error: cartogram -g dnk_processedmap.json -a dnk_data.csv

Hope this information helps.

Many thanks in advance!

**Comment by Udneowi** [comment]
I can see that the generated area_error.dat file contains negative errors as pasted below. Could it be because the orientation of the polygons is wrong?

region 13: cartogram area = -144.169674, relative error = 0.000001
region 2: cartogram area = -144.169595, relative error = 0.000000
region 3: cartogram area = -144.169725, relative error = 0.000001
region 4: cartogram area = -144.170828, relative error = 0.000009
region 5: cartogram area = -144.168648, relative error = -0.000007
region 6: cartogram area = -144.087218, relative error = -0.000571
region 7: cartogram area = -144.168356, relative error = -0.000009
region 8: cartogram area = -144.168844, relative error = -0.000005
region 9: cartogram area = -144.169396, relative error = -0.000001
region 10: cartogram area = -144.167734, relative error = -0.000013
region 11: cartogram area = -144.173253, relative error = 0.000025
region 12: cartogram area = -144.169597, relative error = 0.000000
region 1: cartogram area = -144.169426, relative error = -0.000001
region 14: cartogram area = -144.168784, relative error = -0.000006
region 15: cartogram area = -144.169664, relative error = 0.000001
region 16: cartogram area = -144.170326, relative error = 0.000005
region 17: cartogram area = -144.170792, relative error = 0.000008
region 18: cartogram area = -144.170054, relative error = 0.000003
region 19: cartogram area = -144.169774, relative error = 0.000001
region 20: cartogram area = -144.167147, relative error = -0.000017
region 21: cartogram area = -144.169118, relative error = -0.000003
region 22: cartogram area = -144.169804, relative error = 0.000002
region 23: cartogram area = -144.169563, relative error = -0.000000
region 24: cartogram area = -144.169782, relative error = 0.000001
region 25: cartogram area = -144.171789, relative error = 0.000015
region 26: cartogram area = -144.169664, relative error = 0.000001
region 27: cartogram area = -144.168803, relative error = -0.000005
region 28: cartogram area = -144.169364, relative error = -0.000002
region 29: cartogram area = -144.171715, relative error = 0.000015
region 30: cartogram area = -144.170164, relative error = 0.000004
region 49: cartogram area = -144.169367, relative error = -0.000002
region 32: cartogram area = -144.168690, relative error = -0.000006
region 33: cartogram area = -144.171129, relative error = 0.000011
region 34: cartogram area = -144.168779, relative error = -0.000006
region 35: cartogram area = -144.168398, relative error = -0.000008
region 36: cartogram area = -144.169401, relative error = -0.000001
region 37: cartogram area = -144.169166, relative error = -0.000003
region 38: cartogram area = -144.169655, relative error = 0.000000
region 39: cartogram area = -144.171373, relative error = 0.000012
region 40: cartogram area = -144.170174, relative error = 0.000004
region 41: cartogram area = -144.169313, relative error = -0.000002
region 42: cartogram area = -144.174167, relative error = 0.000032
region 43: cartogram area = -144.171349, relative error = 0.000012
region 44: cartogram area = -144.169780, relative error = 0.000001
region 45: cartogram area = -144.169298, relative error = -0.000002
region 46: cartogram area = -144.171690, relative error = 0.000015
region 47: cartogram area = -144.173819, relative error = 0.000029
region 48: cartogram area = -144.169983, relative error = 0.000003
region 31: cartogram area = -144.169006, relative error = -0.000004
region 50: cartogram area = -144.174758, relative error = 0.000036
region 51: cartogram area = -144.167747, relative error = -0.000013
region 52: cartogram area = -144.173605, relative error = 0.000028
region 53: cartogram area = -144.168983, relative error = -0.000004
region 54: cartogram area = -144.170317, relative error = 0.000005
region 55: cartogram area = -144.171033, relative error = 0.000010
region 56: cartogram area = -144.170855, relative error = 0.000009
region 57: cartogram area = -144.171103, relative error = 0.000011
region 58: cartogram area = -144.166871, relative error = -0.000019
region 59: cartogram area = -144.172309, relative error = 0.000019
region 60: cartogram area = -144.169911, relative error = 0.000002
region 61: cartogram area = -144.168815, relative error = -0.000005
region 72: cartogram area = -144.169510, relative error = -0.000001
region 73: cartogram area = -144.175222, relative error = 0.000039
region 74: cartogram area = -144.169396, relative error = -0.000001
region 75: cartogram area = -144.174470, relative error = 0.000034
region 76: cartogram area = -144.169267, relative error = -0.000002
region 77: cartogram area = -144.169595, relative error = 0.000000
region 62: cartogram area = -144.172375, relative error = 0.000019
region 63: cartogram area = -144.168243, relative error = -0.000009
region 64: cartogram area = -144.172593, relative error = 0.000021
region 65: cartogram area = -144.169420, relative error = -0.000001
region 66: cartogram area = -144.170153, relative error = 0.000004
region 67: cartogram area = -144.170865, relative error = 0.000009
region 68: cartogram area = -144.169490, relative error = -0.000001
region 69: cartogram area = -144.168175, relative error = -0.000010
region 70: cartogram area = -144.170864, relative error = 0.000009
region 71: cartogram area = -144.193622, relative error = 0.000167
region 84: cartogram area = -144.168375, relative error = -0.000008
region 85: cartogram area = -144.172354, relative error = 0.000019
region 86: cartogram area = -144.169439, relative error = -0.000001
region 87: cartogram area = -144.169384, relative error = -0.000001
region 88: cartogram area = -144.171173, relative error = 0.000011
region 89: cartogram area = -144.171099, relative error = 0.000010
region 90: cartogram area = -144.171358, relative error = 0.000012
region 91: cartogram area = -144.169949, relative error = 0.000003
region 92: cartogram area = -144.169503, relative error = -0.000001
region 93: cartogram area = -144.171589, relative error = 0.000014
region 94: cartogram area = -144.169663, relative error = 0.000001
region 95: cartogram area = -144.171123, relative error = 0.000011
region 96: cartogram area = -144.171822, relative error = 0.000016
region 97: cartogram area = -144.170009, relative error = 0.000003
region 98: cartogram area = -144.168139, relative error = -0.000010
region 99: cartogram area = -144.168218, relative error = -0.000009
region 78: cartogram area = -144.175012, relative error = 0.000038
region 79: cartogram area = -144.171083, relative error = 0.000010
region 80: cartogram area = -144.170069, relative error = 0.000003
region 81: cartogram area = -144.168759, relative error = -0.000006
region 82: cartogram area = -144.168897, relative error = -0.000005
region 83: cartogram area = -144.169292, relative error = -0.000002

**Comment by mgastner** [comment]
It seems to work if you change the sign of the area in `polygon_area()`. I replaced lines 387-391 in read_map.c with these lines:

```
  for (i=0; i<ncrns-1; i++)
    area +=
      0.5 * (polygon[i].x+polygon[i+1].x) * (polygon[i+1].y-polygon[i].y);
  return area += 0.5 * (polygon[ncrns-1].x+polygon[0].x) *
                 (polygon[0].y-polygon[ncrns-1].y);
```

The result looks as expected.

We are currently working on an improved C++ version of the cartogram code. Among many other improvements, it will not make any assumption about the polygons' winding direction. We still need a few more weeks before we are ready to transition to the new version. Meanwhile, I suggest to make the edit above.

**Comment by Udneowi** [comment]
Thanks! It did fix the problem with creating the GeoJSON file!
However I'm not able to visualise it using geopandas in Python and I think it it's because the generated bounding box is not correct. I'll look a bit more into it let you know if I figure out the problem :)

**Comment by mgastner** [comment]
I had some problems importing the generated GeoJSON files into R in the past. Your problem might be related. I suspect that we currently do not strictly conform to the GeoJSON standard. (Another issue that the next version will fix.) A workaround is to open the GeoJSON in Mapshaper and export it again.

**Comment by Udneowi** [comment]
Yeah that seems like it's the case. Loading in the GeoJSON and just stripping all meta information except the geometry to remake a GeoDataFrame solved the issue. 

Thanks a lot for all the help :) I really appreciate it!
