### ISSUE TITLE
Cartogram generation gets stuck in ffb_integrate()

### ISSUE THREAD

**Issue by byambajav** [Flow-Based-Cartograms/go_cart#3]
The provided examples run fine on my machine. But when I try to run the cartogram generation with my [data](https://www.dropbox.com/sh/4hzwgdllpb1a49f/AAAdcb8n37JXVCFXKRra_E4za?dl=0), it gets stuck in the `ffb_integrate()` step. Do I need to pre-process my data to satisfy some conditions or is it a bug in the tool?

**Comment by pratyushmore** [comment]
Hi @byambajav ,

We use ArcGIS' convention that polygons whose points are provided in a clock-wise direction are treated as positive areas, whereas those whose points are provided in an anti-clockwise direction are treated as negative areas. In your sample data, I believe Polygon 14 is provided in an anti-clockwise direction, which causes its area to be negative. This leads to an overall negative average density, which prevents the integrator from converging.

Further details and mathematics are provided in the code. Link to specific file and line:

https://github.com/Flow-Based-Cartograms/go_cart/blob/53dbf84cccb3b3351c83e6a236890a03fa36966f/cartogram_generator/fill_with_density.c#L177

Hope this helps!

**Comment by pratyushmore** [comment]
I have further verified that this is the problem. When I remove the anti-clockwise check, I obtain the following figure, which is consistent with your data:

![cartogram](https://user-images.githubusercontent.com/16759939/36936356-619bfcd6-1f3f-11e8-92fd-3b1a840d5b7f.png)

**Comment by byambajav** [comment]
Hi @pratyushmore,

After fixing my data to conform to the conventions (clockwise for outer polygons, anti-clockwise for holes), I was able to run the cartogram generation.

Thanks for your help.
