### ISSUE TITLE
convert .shp file to  .gen file

### ISSUE THREAD

**Issue by BihanHu** [Flow-Based-Cartograms/go_cart#6]
The report is excellent！But  I'm not familiar with the .gen data format,how to convert the .shp file to .gen file?

**Comment by mgastner** [comment]
Thank you for your email. You're right that we should have added a description of the .gen format in the README. I've updated it just now.

Many years ago, ArcGIS could convert from .shp to .gen. Here is more information: http://courses.washington.edu/gis250/lessons/data_export/index.html#generate.

Would you find it useful if I upload an R script that can convert from .shp to .gen?

**Comment by BihanHu** [comment]
Thanks for replying. It will help me a lot!

**Comment by mgastner** [comment]
I haven't forgotten about your request. I'm currently bogged down by teaching. I have some R code that has worked fine in specific applications. But to make it GitHub worthy, I'd need to spend a little bit more time on it. If it's urgent for you, please email me at michael.gastner@yale-nus.edu.sg and request the code that hasn't yet been cleaned up.

**Comment by pratyushmore** [comment]
We are moving towards GeoJSON, so this issue will no longer be pertinent. Closing it!

**Comment by VestuV** [comment]
> Thank you for your email. You're right that we should have added a description of the .gen format in the README. I've updated it just now.
> 
> 
> 
> Many years ago, ArcGIS could convert from .shp to .gen. Here is more information: http://courses.washington.edu/gis250/lessons/data_export/index.html#generate.
> 
> 
> 
> Would you find it useful if I upload an R script that can convert from .shp to .gen?

It would be realy usefull to have an R Skript to produce .gen datas. Im an Engineer and we work a lot with R at my Company.

**Comment by mgastner** [comment]
I made the repo with the R script public: [https://github.com/mgastner/shp2gen](https://github.com/mgastner/shp2gen). Support for .gen is going to be dropped in the next version in favor of GeoJSON.
