### ISSUE TITLE
Data Source Worldmap

### ISSUE THREAD

**Issue by fabiankraxenberger** [Flow-Based-Cartograms/go_cart#7]
Hey! 
I´m new to Github and not conversant with the common rules. 
Never the less.... Do you know where i can get any Open Source Data (Cartesian coordinate) for a World Map/Europe ? 

Greetings Fabian

**Comment by mgastner** [comment]
Dear Fabian,

Thank you for your message. If by Europe you mean the European Union, you may find something useful at Eurostat:
https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries

For world data, perhaps Natural Earth is your friend:
https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
You may still need to reproject the data before running our code.

I recently posted an R script on GitHub for converting from shapefile to the .gen format needed to run our code:
https://github.com/mgastner/shp2gen

Hope this helps,
Michael
